trigger:
- main

pool:
  name: Default   # Your self-hosted agent

steps:

- checkout: self

- script: |
    echo "Upgrading pip..."
    python -m pip install --upgrade pip
  displayName: "Upgrade pip"

- script: |
    echo "Installing dependencies..."
    if exist requirements.txt pip install -r requirements.txt
  displayName: "Install Dependencies"

- script: |
    echo "Running Python Application..."
    python main.py
  displayName: "Run Application"

- script: |
    echo "CI Pipeline Completed Successfully"
  displayName: "Completion Message"
