trigger:
- main

pool:
  name: Default

steps:

- checkout: self

- script: |
    echo Checking Python version...
    where python
    python --version
  displayName: "Check Python"

- script: |
    echo Running Application...
    python main.py
  displayName: "Run Application"

- script: |
    echo CI Pipeline Completed Successfully
  displayName: "Completion Message"
